"""         https://projecteuler.net/problem=2      """
"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, 
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the 
even-valued terms.
"""

fl = [0, 1]

[fl.append(fl[-1]+fl[-2]) for i in range(40)]

# print(fl)

fl1 = [x for x in fl if x%2 == 0 and x < 4000000]
print(fl1)
print(sum(fl1))

fl2 = [fl[i] for i in range(0, len(fl), 3) if fl[i] < 4000000]
print(fl2)
print(sum(fl2))

